name: annotate
version: 0.0.3
author: Matthew Franglen <matthew.franglen@gmail.com>
homepage: https://github.com/matthewfranglen/dart-annotate
description: Easy way to find or test for annotations on object, classes, etc.
dependencies:
  patch_mirrors: ">=0.0.1 <0.1.0"
dev_dependencies:
  behave:
    git: git@github.com:matthewfranglen/dart-behave.git
  unittest: any
